import { StyleSheet } from 'react-native';
import { Button } from 'react-native/types_generated/index';

export const estilos = StyleSheet.create({
  areaSegura: {
    flex: 1,
    backgroundColor: '#f4f7ff',
  },
  burbujaSuperiorFondo: {
    position: 'absolute',
    top: -130,
    right: -90,
    width: 340,
    height: 340,
    borderRadius: 170,
    backgroundColor: '#dfeaff',
    borderWidth: 18,
    borderColor: '#cfe0ff',
  },
  burbujaInferiorFondo: {
    position: 'absolute',
    bottom: -140,
    left: -110,
    width: 390,
    height: 390,
    borderRadius: 195,
    backgroundColor: '#fce9ef',
    borderWidth: 18,
    borderColor: '#f7dfe8',
  },
  contenedor: {
    flex: 1,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 30,
    paddingBottom: 18,
    paddingHorizontal: 20,
  },
  carta: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: '#ffffff',
    borderRadius: 30,
    marginTop: 18,
    paddingVertical: 22,
    paddingHorizontal: 20,
    shadowColor: '#0f214a',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.13,
    shadowRadius: 16,
    elevation: 7,
    alignItems: 'center',
  },
  filaMarca: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 14,
  },
  logoPequeno: {
    width: 32,
    height: 32,
    borderRadius: 10,
    marginRight: 10,
  },
  textoMarca: {
    color: '#17233b',
    fontSize: 34,
    fontWeight: '900',
    letterSpacing: 0.6,
  },
  imagen: {
    width: 220,
    height: 220,
    borderRadius: 110,
    borderWidth: 6,
    borderColor: '#eef2ff',
    backgroundColor: '#ffffff',
  },
  subtitulo: {
    marginTop: 12,
    color: '#51607b',
    fontSize: 14,
    fontWeight: '600',
  },
  contenedorBotones: {
    width: '100%',
    maxWidth: 360,
    marginTop: 28,
    marginBottom: 0,
    gap: 14,
  },
  contenedorSecundario: {
    width: '100%',
    minHeight: 62,
    borderRadius: 18,
    backgroundColor: '#2f5ae9',
    shadowColor: '#18338f',
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.2,
    shadowRadius: 11,
    elevation: 4,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  textoSecundario: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: 'bold',
  },
  contenedorTerciario: {
    width: '100%',
    minHeight: 62,
    borderRadius: 18,
    borderWidth: 3,
    borderColor: '#2f5ae959',
    backgroundColor: '#ffffff',
    shadowColor: '#18338f',
    shadowOffset: { width: 0, height: 7 },
    shadowOpacity: 0.18,
    shadowRadius: 11,
    elevation: 4,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  textoTerciario: {
    color: '#2f5ae9',
    fontSize: 18,
    fontWeight: 'bold',
  },
  derechosAutor: {
    color: '#61708f',
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'center',
    marginTop: 18,
  },
  titulos: {
    marginBottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    top: 100,
    left: 0,
    right: 0,
    height: 100,
  },
  textoTitulos: {
    fontSize: 58,
    fontWeight: '700',
    color: '#17233b',
  },
});



